### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by RomainMon** [Promo-Geonum/Mapbox_et_3D#1]
* [X] Créer un objet map avec un fond de plan Mapbox
* [ ] Ajouter les geojson d'intérêt : bâti, arbres de Lyon (arbres d'alignement ou EVA)
* [x] Extrusion des objets
* [x] Personnalisation du style
* [ ] Gestion de la caméra ?
* [x] Essai de ciel vespéral / nocturne
* [x] Ajout d'un MNT ? (cf data grand lyon : flux WMS image 5m RS)
* [ ] Slide sur les types de licence (évolution actuelle des licences Mapbox)
* [ ] Mise en page du tuto (code, licences, etc.)
* [x] Fumer une clope
* [x] tester les données BD Topo sur Part-Dieu (paramètre hauteur) 
* [x] tester les données BD Topo sur Amphi (z min, z max) 
* [ ] tuto: https://docs.mapbox.com/mapbox-gl-js/example/3d-buildings/ les toits sont plats, essayer d'améliorer cela
